
#ifndef TIMERS_CONFIG_H_
#define TIMERS_CONFIG_H_

/*
TIMER0_PRESCALER_STOP
TIMER0_PRESCALER_1
TIMER0_PRESCALER_8
TIMER0_PRESCALER_64
TIMER0_PRESCALER_256
TIMER0_PRESCALER_1024
*/
#define TIMER0_PRESCALER   TIMER0_PRESCALER_8

#define TIMER0_COMPARE_MATCH_VALUE   200

/*
TIMER0_CTC_MODE
TIMER0_OVF_MODE
TIMER0_Fast_PWM_MODE
TIMER0_Phase_Correct_MODE
*/
#define  TIMER0_WAVE_GEN_MODE   TIMER0_CTC_MODE




#endif
